services:
  # wesql:
  #   container_name: dropbucket_wesql
  #   image: apecloud/wesql-server:8.0.35-0.1.0_beta3.38
  #   environment:
  #     # Configuración básica de la base de datos
  #     # - MYSQL_ROOT_PASSWORD=${POSTGRES_PASSWORD}
  #     # - MYSQL_DATABASE=${POSTGRES_DB}
  #     # - MYSQL_USER=${POSTGRES_USER}
  #     # - MYSQL_PASSWORD=${POSTGRES_PASSWORD}
  #     - MYSQL_DATABASE=${POSTGRES_DB}
  #     - MYSQL_USER=${POSTGRES_USER}
  #     - MYSQL_PASSWORD=${POSTGRES_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${POSTGRES_PASSWORD}
  #     - MYSQL_ROOT_HOST=%


  #     # Configuración de S3
  #     # - AWS_ACCESS_KEY_ID=${WESQL_ACCESS_KEY}
  #     # - AWS_SECRET_ACCESS_KEY=${WESQL_SECRET_KEY}
  #     # - S3_BUCKET_NAME=${WESQL_BUCKET}
  #     # - S3_ENDPOINT=s3.us-east-1.amazonaws.com
  #     # - S3_REGION=${AWS_REGION}
  #     # - S3_BACKUP_PATH=/backups
  #     # - S3_STORAGE_CLASS=STANDARD
  #     - WESQL_OBJECTSTORE_ACCESS_KEY=${WESQL_ACCESS_KEY}
  #     - WESQL_OBJECTSTORE_SECRET_KEY=${WESQL_SECRET_KEY}
  #     - WESQL_OBJECTSTORE_BUCKET=${WESQL_BUCKET}
  #     - WESQL_OBJECTSTORE_REGION=${AWS_REGION}
  #     - WESQL_OBJECTSTORE_ENDPOINT=s3.us-east-1.amazonaws.com
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - wesql_volume:/var/lib/mysql
  #   restart: unless-stopped
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci
  #     - --plugin-load-add=s3_storage_engine.so
  # volumes:
  #   dropbucket_volume:
  #     external: true
  #   wesql_volume:
  #     external: true

  # SIN DOCKERFILE
#   postgres:
#     container_name: dropbucket_postgres
#     image: postgres:13.16
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     ports:
#       - 5432:5432
#     volumes:
#       - dropbucket_volume:/var/lib/postgresql/data

#   nestjs:
#     container_name: dropbucket_nestjs
#     image: node:22.7.0-alpine3.20
#     working_dir: /app
#     restart: unless-stopped
#     ports:
#       - 3000:3000
#     volumes:
#       - ./:/app
#     environment:
#       - NODE_ENV=development
#     command: sh -c "npm install"
#     # command: sh -c "npm install -g @nestjs/cli && npm run start:devtsnd"
#     depends_on:
#       - postgres

# volumes:
#   dropbucket_volume:
#     external: true
#   wesql_volume:
#     external: true



  

  # CON DOCKERFILE

  postgres:
    container_name: dropbucket_postgres
    image: postgres:13.16
    # working_dir: /app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - dropbucket_volume:/var/lib/postgresql/data    
  nestjs:
    container_name: dropbucket_nestjs
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      # - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma/schema.prisma:/app/prisma/schema.prisma
      - ./prisma/seeders.ts:/app/prisma/seeders.ts
      # Exclude node_modules and prisma generated files
      - /app/node_modules
      - /app/prisma/generated
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

volumes:
  dropbucket_volume:
    external: true
  #   wesql_volume:
  #     external: true


  # Con base de datos en aws
  # nestjs:
  #   container_name: dropbucket_nestjs
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: development
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/app
  #     - ./src:/app/src
  #     - ./test:/app/test
  #     - ./prisma/schema.prisma:/app/prisma/schema.prisma
  #     - ./prisma/seeders.ts:/app/prisma/seeders.ts
  #     # Exclude node_modules and prisma generated files
  #     # - /app/node_modules
  #     # - /app/prisma/generated
  #   environment:
  #     - NODE_ENV=development




  # comandos directos

  # docker volume create --driver local \
  #     --opt type=none \
  #     --opt device=/mnt/efs/fs1 \
  #     --opt o=bind \
  #     dropbucket-asistir-postgres

  #  docker run -d \
  #   --name postgres-dropbucket \
  #   -v dropbucket-asistir-postgres:/var/lib/postgresql/data \
  #   -e POSTGRES_USER=admin \
  #   -e POSTGRES_PASSWORD=12345 \
  #   -e POSTGRES_DB=dropbucket \
  #   -p 5432:5432 \
  #   postgres:13.16
